import type { Metadata } from "next";
import "@/app/globals.css";
import ThemeProvider from "@/components/ThemeProvider";

import { Unbounded } from "next/font/google";
const geistSans = Unbounded({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Unbounded({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute={"class"} enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
